# Generated by Django 5.1 on 2024-08-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsApp', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_id',
            new_name='fcm_token',
        ),
    ]
